api/urls.py
from django.urls import path
from api.product.views import CategoryAPI
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register('category-api', CategoryAPI)

urlpatterns = [
]

urlpatterns += router.urls

product/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('logout', UserLogout.as_view(), name='logout'),
    path('category/<slug:slug>', CategoryDetailView.as_view(), name="category"),
    path('cart/', CartView.as_view(), name="cart"),
    path('category/<slug:category_id>/<slug:slug>', ProductDetailView.as_view(), name="detail_product"),
    path('add/<slug:product_model>/<slug:slug>', AddToCartView.as_view(), name="add-to-cart"),
    path('delete/<slug:product_model>/<slug:slug>', DeleteFromCartView.as_view(), name="delete-from-cart"),
    path('change/<slug:product_model>/<slug:slug>', ChangeCountView.as_view(), name="change-count"),
    path('review/<slug:product_model>/<slug:slug>', AddReviewView.as_view(), name="add-review")
]

shop/urls.py
import debug_toolbar
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/', include('api.urls'))
]

urlpatterns += i18n_patterns(
    path('', include('product.urls')),
    path('order/', include('order.urls')),
    path('accounts/', include('profil.urls'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/models.py
import datetime
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone
from order.models import Order


User = get_user_model()


class Category(models.Model):
    """Модель категорій"""
    name = models.CharField(max_length=255, verbose_name="Ім'я")
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name_uk

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"


class Product(models.Model):
    """Модель продуктів"""
    category = models.ForeignKey(Category, verbose_name="Категорії", on_delete=models.CASCADE)
    title = models.CharField(max_length=255, db_index=True, verbose_name="Ім'я")
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='images_product/', verbose_name="Фото", null=True, blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=1, verbose_name="Ціна")
    quantity_in_stock = models.PositiveIntegerField(verbose_name="Кількість на складі", default=0)
    date = models.DateTimeField(verbose_name="Дата", auto_now_add=True)

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукти"

    def checking_availability_in_stock(self):
        return self.quantity_in_stock > 0

    def __str__(self):
        return f'Продукт {self.title} Категорії {self.category}'

    def get_brand_product(self):
        return Product.objects.filter(
            spec__key_uk='Бренд', slug=self.slug).values('spec__value_uk').first()['spec__value_uk']

    def get_absolute_url(self):
        return reverse('detail_product', kwargs={'category_id': self.category.slug, 'slug': self.slug})

    def new_product(self):
        return self.date >= (timezone.now() - datetime.timedelta(days=1))


class Spec(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    key = models.CharField(max_length=50)
    value = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Специфікація'
        verbose_name_plural = 'Специфікації'


class ShortImgProduct(models.Model):
    mdl = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    img = models.ImageField(upload_to='product/', verbose_name="Фото")

    def __str__(self):
        return self.mdl.title

    class Meta:
        verbose_name = 'Кадри ноутбука'
        verbose_name_plural = 'Кадри ноутбуків'


class CartProduct(models.Model):
    """Карточка товара"""
    user = models.ForeignKey('Customer', on_delete=models.CASCADE, verbose_name="Покупець")
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE, verbose_name="Корзина", related_name="related_products")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    count = models.PositiveIntegerField(default=1)
    all_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name="Вся сума")

    def __str__(self):
        return f"{self.id}"

    def save(self, *args, **kwargs):
        self.all_price = self.count * self.product.price
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Карта Продукта"
        verbose_name_plural = "Карта Продуктів"


class Customer(models.Model):
    """Покупець"""
    user = models.ForeignKey(User, verbose_name="Покупець", on_delete=models.CASCADE)
    order = models.ManyToManyField('order.Order', related_name='orders_customer', verbose_name="Замовлення")

    def __str__(self):
        return self.user.first_name

    class Meta:
        verbose_name = "Покупець"
        verbose_name_plural = "Покупці"


class Cart(models.Model):
    """Корзина"""
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, verbose_name="Покупець")
    products = models.ManyToManyField(CartProduct, blank=True, related_name="related_cart")
    all_product = models.PositiveIntegerField(default=0, null=True, blank=True)
    all_price = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True, verbose_name="Вся сума")
    discount = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name="Сума із знижкою")
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.customer} - {self.products}"

    def count_product_in_cart(self):
        c = self.products.aggregate(models.Sum('count'))
        if c['count__sum'] is None:
            return {'count__sum': 0}
        return c

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзина"


class Review(models.Model):
    """Відгуки"""
    review = models.TextField(verbose_name="Відгук")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review

    class Meta:
        verbose_name = "Відгук"
        verbose_name_plural = "Відгуки"

product/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review']

api/product/views.py
from rest_framework.viewsets import ModelViewSet
from .serializers import CategorySerializers
from product.models import Category


class CategoryAPI(ModelViewSet):

    serializer_class = CategorySerializers
    queryset = Category.objects.all()

product/views.py
from typing import List

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, CreateView

from product.forms import ReviewForm
from product.mixins import CartMixin, save_cart, CommonMixin
from product.models import Category, Product, CartProduct, Review, Cart


class HomeView(CartMixin, View):
    """Home page"""
    def get(self, request, *args, **kwargs):
        category = Category.objects.all()
        product = Product.objects.all().order_by('-id')[:4].select_related('category')
        context = {
            'product': product,
            'categories': category,
            'cart': self.cart
        }
        return render(request, 'product/base.html', context)


class CategoryDetailView(CommonMixin, CartMixin, DetailView):
    """Category product"""
    model = Category
    template_name = 'product/detail_page.html'
    context_object_name = 'category'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.category_slug = self.kwargs.get('slug')

        context['specifications'] = Product.objects.filter(
            category__slug=self.category_slug).values('spec__key', 'spec__value').distinct()

        context['cart'] = self.cart
        context['q'] = self.get_filter_date()
        context['name'] = self.get_auto_name()

        if self.find():
            context['find'] = self._page_pagination(self.find())
        elif self.request.GET.getlist('specification'):
            context['filter_product'] = self._page_pagination(
                Product.objects.select_related('category').filter(
                    spec__value__in=self.request.GET.getlist('specification'),
                    category__slug=self.category_slug).distinct())
        else:
            context['products'] = self._page_pagination(Product.objects.select_related('category').filter(
                category__slug=self.category_slug)[::-1])

        return context

    def find(self):
        """Search"""
        q = self.request.GET.get('q')
        if q:
            return Product.objects.select_related('category').filter(title__istartswith=q,
                                                                     category__slug=self.category_slug)

    def get_auto_name(self):
        """Автоматичні імена, для пошуку"""
        qs = Product.objects.filter(category__slug=self.category_slug).values_list('title', flat=True)
        return list(qs)

    def get_filter_date(self):
        """Get link"""
        p = self.request.GET
        s = []
        for i in p:
            if i != 'page':
                s.append(''.join([f'{i}={j}&' for j in self.request.GET.getlist(i)]))
            else:
                break
        link = ''.join(s)
        return link

    def _page_pagination(self, qs: List[Product]):
        """Pagination"""
        element = Paginator(qs, 9)
        page_num = self.request.GET.get('page', 1)

        try:
            page = element.page(page_num)
        except EmptyPage:
            page = element.page(1)
        return page


class ProductDetailView(CommonMixin, CartMixin, DetailView):
    """Separate product"""
    model = Product
    queryset = Product.objects.select_related('category').prefetch_related('shortimgproduct_set')
    template_name = 'product/detail_product.html'
    context_object_name = "product"
    slug_url_kwarg = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = self.cart
        context['form'] = ReviewForm()
        context['review'] = Review.objects.filter(product__slug=self.kwargs.get('slug')).select_related('user')
        return context


class CartView(LoginRequiredMixin, CartMixin, View):
    """Basket"""
    login_url = reverse_lazy("login")

    def get(self, request, *args, **kwargs):
        context = {
            'cart': self.check_correct_basket(),
            'categories': Category.objects.all()
        }
        return render(request, 'product/cart.html', context)

    def check_correct_basket(self):
        """This method checks all products for stock"""
        for i in self.cart.products.all():
            if i.product.quantity_in_stock == 0:
                self.cart.products.remove(i)
                i.delete()
        save_cart(self.cart)
        return self.cart


class AddToCartView(LoginRequiredMixin, CartMixin, View):
    """Add product in basket"""
    login_url = reverse_lazy("login")

    def get(self, request, *args, **kwargs):
        slug_product = kwargs.get('slug')
        product = Product.objects.filter(slug=slug_product).first()
        cart_product, created = CartProduct.objects.get_or_create(
            user=self.cart.customer, cart=self.cart, product=product
        )
        if created:
            self.cart.products.add(cart_product)
        save_cart(self.cart)
        return redirect('cart')


class DeleteFromCartView(CartMixin, View):
    """Delete product basket"""
    def get(self, request, *args, **kwargs):
        slug_product = kwargs.get('slug')
        product = Product.objects.filter(slug=slug_product).first()
        cart_product, created = CartProduct.objects.get_or_create(
            user=self.cart.customer, cart=self.cart, product=product
        )
        self.cart.products.remove(cart_product)
        cart_product.delete()
        save_cart(self.cart)
        return redirect('cart')


class ChangeCountView(CartMixin, View):
    """Change quantity"""
    def post(self, request, *args, **kwargs):
        slug_product = kwargs.get('slug')
        product = Product.objects.filter(slug=slug_product).first()
        cart_product = CartProduct.objects.get(
            user=self.cart.customer, cart=self.cart, product=product
        )

        count = int(request.POST.get('count'))
        cart_product.count = count
        cart_product.save()
        save_cart(self.cart)
        return redirect('cart')


class UserLogout(LogoutView):
    """Class for profile exit"""
    next_page = reverse_lazy('login')


class AddReviewView(LoginRequiredMixin, CreateView):
    """Add review"""
    model = Review
    form_class = ReviewForm
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.review = self.request.POST.get('review')
        form.instance.user = self.request.user
        form.instance.product = Product.objects.filter(slug=self.kwargs.get('slug')).first()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('detail_product', kwargs={'category_id': self.kwargs.get('category_id'),
                                                      'slug': self.kwargs.get('slug')})

product/templates/product/inc/cart_product.html
{% load static %}
{% load i18n %}
{% load static i18n %}
<div class="cart">

    {% if p.new_product %}
        <img src="{% static 'product/img/завантаження (1dwq).png' %}" class="icon">
    {% endif %}

    <a href="{% url 'detail_product' category_id=p.category.slug slug=p.slug %}">
        <img src="{{ p.image.url }}" class='img-product' style="cursor: pointer">
    </a>

    <p class="tp"><a href="{% url 'detail_product' category_id=p.category.slug slug=p.slug %}"
                     class="title-product">{{ p.title }}</a></p>
    <p class="price">{{ p.price }} {% trans 'грн' %}</p>

    {% if not p.checking_availability_in_stock %}
        <a href="#" class="buy" style="background: #7D26CD">
            {% trans 'Відсутній' %}
        </a>
    {% else %}
        <a href="{% url 'add-to-cart' product_model=p.category.slug slug=p.slug %}" class="buy">
            {% trans 'В корзину' %}
            <img src="{% static 'product/img/2849824-basket-buy-market-multimedia-shop-shopping-store_107977.png' %}">
        </a>
    {% endif %}

</div>

product/templates/product/inc/notebook_filter.html
{% load static %}
{% load i18n %}
{% load static i18n %}
<ul style="list-style: none;">
   <li class="title-filter" onclick="showFilter('nb', 'nimg')">{% trans 'Бренд' %}</li>
   <img src="{% static 'product/img/strilka.png' %}" id="nimg" width="25px" style="margin-top: -28px; margin-left: 58px;"></li>
   <div class="filter" id="nb">
    {% for b in specifications %}
            {% if b.spec__key  == 'Бренд' or b.spec__key  == 'Brand' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
    {% endfor %}
   </div>
    <br>

    <li class="title-filter" onclick="showFilter('nd', 'dimg')">{% trans 'Діагональ' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="dimg" width="25px"
         style="margin-top: -28px; margin-left: 83px;"></li>
    <div class="filter" id="nd">
        {% for b in specifications %}
            {% if b.spec__key  == 'Діагональ екрану' or b.spec__key  == 'Screen diagonal' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('no', 'noimg')">{% trans 'ОС' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="noimg" width="25px" style="margin-top: -28px; margin-left: 32px;"></li>
    <div class="filter" id="no">
        {% for b in specifications %}
            {% if b.spec__key  == 'ОС' or b.spec__key  == 'OS' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('nc', 'kimg')">{% trans 'Кількість ядер' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="kimg" width="25px"
         style="margin-top: -28.5px; margin-left: 125px;"></li>
    <div class="filter" id="nc">
        {% for b in specifications %}
            {% if b.spec__key  == 'Кількість ядер' or b.spec__key  == 'Number of cores' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
</ul>

product/templates/product/inc/paginator.html
<div class="paginator">
    {% if find %}


        {% if find.paginator.num_pages > 1 %}
            {% for i in find.paginator.page_range %}
                {% if find.number == i %}
                    <a href="{% url 'category' category.slug %}?{% if q %}{{ q }}{% endif %}page={{ i }}"
                       class="button-num active">{{ i }}</a>
                {% elif i > find.number|add:-3 and i < find.number|add:3 %}
                    <a href="{% url 'category' category.slug %}?{% if q %}{{ q }}{% endif %}page={{ i }}"
                       class="button-num">{{ i }}</a>
                {% endif %}
            {% endfor %}
        {% endif %}


    {% elif filter_product %}
        {% if filter_product.paginator.num_pages > 1 %}
            {% if filter_product.has_previous %}
                <a href="{% url 'category' category.slug %}?{{ q }}page={{ 1 }}"
               class="button-pag">&laquo;</a>

                <a href="{% url 'category' category.slug %}?
                        {{ q }}page={{ filter_product.previous_page_number }}"
                   class="button-pag">&#8249;</a>
            {% endif %}

            {% for i in filter_product.paginator.page_range %}
                {% if filter_product.number == i %}
                    <a href="{% url 'category' category.slug %}?{% if q %}{{ q }}{% endif %}page={{ i }}"
                       class="button-num active">{{ i }}</a>
                {% elif i > filter_product.number|add:-3 and i < filter_product.number|add:3 %}
                    <a href="{% url 'category' category.slug %}?{% if q %}{{ q }}{% endif %}page={{ i }}"
                       class="button-num">{{ i }}</a>
                {% endif %}
            {% endfor %}

            {% if filter_product.has_next %}
                <a href="{% url 'category' category.slug %}?
                        {{ q }}page={{ filter_product.next_page_number }}"
                   class="button-pag">&#8250;</a>

                <a href="{% url 'category' category.slug %}?
                    {{ q }}page={{ filter_product.paginator.num_pages }}"
                   class="button-pag">&raquo;</a>

            {% endif %}
        {% endif %}


    {% else %}
        {% if products.paginator.num_pages > 1 %}
            {% if products.has_previous %}
                <a href="{% url 'category' category.slug %}?page={{ 1 }}"
                   class="button-pag">&laquo;</a>


                <a href="{% url 'category' category.slug %}?page={{ products.previous_page_number }}"
                   class="button-pag">&#8249;</a>
            {% endif %}

            {% for i in products.paginator.page_range %}
                {% if products.number == i %}
                    <a href="{% url 'category' category.slug %}?page={{ i }}"
                       class="button-num active">{{ i }}</a>
                {% elif i > products.number|add:-3 and i < products.number|add:3 %}
                    <a href="{% url 'category' category.slug %}?page={{ i }}"
                       class="button-num">{{ i }}</a>
                {% endif %}
            {% endfor %}

            {% if products.has_next %}
                <a href="{% url 'category' category.slug %}?page={{ products.next_page_number }}"
                   class="button-pag">&#8250;</a>

                <a href="{% url 'category' category.slug %}?page={{ products.paginator.num_pages }}"
                   class="button-pag">&raquo;</a>

            {% endif %}
        {% endif %}

    {% endif %}
</div>

product/templates/product/inc/pc_filter.html
{% load static %}
{% load i18n %}
{% load static i18n %}
<ul style="list-style: none;">
    <li class="title-filter" onclick="showFilter('pcb', 'pcimg')">{% trans 'Бренд' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="pcimg" width="25px" style="margin-top: -27px; margin-left: 58px;"></li>
    <div class="filter" id="pcb">
        {% for b in specifications %}
            {% if b.spec__key  == 'Бренд' or b.spec__key  == 'Brand'  %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('pct', 'timg')">{% trans 'Тип' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="timg" width="25px" style="margin-top: -28px; margin-left: 40px;"></li>
    <div class="filter" id="pct">
        {% for b in specifications %}
            {% if b.spec__key  == 'Тип' or b.spec__key  == 'Type'%}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('pcp', 'pcpimg')">{% trans 'Процесор' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="pcpimg" width="25px" style="margin-top: -28px; margin-left: 83px;"></li>
    <div class="filter" id="pcp">
        {% for b in specifications %}
            {% if b.spec__key  == 'Процесор' or b.spec__key  == 'Processor' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('pcv', 'vimg')">{% trans 'Відео карта' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="vimg" width="25px" style="margin-top: -28px; margin-left: 98px;"></li>
    <div class="filter" id="pcv">
        {% for b in specifications %}
            {% if b.spec__key  == 'Відеокарта' or b.spec__key  == 'Video card' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
</ul>

product/templates/product/inc/phone_filter.html
{% load static %}
{% load i18n %}
{% load static i18n %}
<ul style="list-style: none;">
    <li class="title-filter" onclick="showFilter('pb', 'pimg')" style="margin-bottom: -2px">{% trans 'Бренд' %}
        <img src="{% static 'product/img/strilka.png' %}" id="pimg" width="25px" style="margin-top: -4px; margin-left: -3px;"></li>
    <div class="filter" id="pb">
        {% for b in specifications %}
            {% if b.spec__key  == 'Бренд' or b.spec__key  == 'Brand' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('db', 'dimg')">{% trans 'Діагональ' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="dimg" width="25px"
         style="margin-top: -28px; margin-left: 84px;"></li>
    <div class="filter" id="db">
        {% for b in specifications %}
            {% if b.spec__key  == 'Діагональ екрану' or b.spec__key  == 'Screen diagonal' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('op', 'oimg')">{% trans 'Оператива' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="oimg" width="25px"
         style="margin-top: -27px; margin-left: 90px;"></li>
    <div class="filter" id="op">
        {% for b in specifications %}
            {% if b.spec__key  == "Оперативна пам'ять" or b.spec__key  == 'RAM' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
</ul>

product/templates/product/inc/slider.html
<div class="slide fade">
    <img src="{{ product.image.url }}"
         class="img1">
</div>
{% for i in product.shortimgproduct_set.all %}
    <div class="slide fade">
        <img src="{{ i.img.url }}"
             class="img1">
    </div>
{% endfor %}

product/templates/product/inc/specification.html
<table>
    <tbody>
       {% for i in product.spec_set.all %}
        <tr class="info">
            <td class="item">{{ i.key }}</td>
            <td class="value">{{ i.value }}</td>
        </tr>
       {% endfor %}
    </tbody>
</table>

product/templates/product/inc/tablet_filter.html
{% load static %}
{% load i18n %}
{% load static i18n %}
<ul style="list-style: none;">
    <li class="title-filter" onclick="showFilter('tb', 'bimg')">{% trans 'Бренд' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="bimg" width="25px" style="margin-top: -28px; margin-left: 60px;"></li>
    <div class="filter" id="tb">
        {% for b in specifications %}
            {% if b.spec__key  == 'Бренд' or b.spec__key  == 'Brand' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('td', 'dimg')">{% trans 'Діагональ' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="dimg" width="25px" style="margin-top: -28px; margin-left: 83px;"></li>
    <div class="filter" id="td">
        {% for b in specifications %}
            {% if b.spec__key  == 'Діагональ' or b.spec__key  == 'Diagonal' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('tr', 'oimg')">{% trans 'Оператива' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="oimg" width="25px" style="margin-top: -28px; margin-left: 91px;"></li>
    <div class="filter" id="tr">
        {% for b in specifications %}
            {% if b.spec__key  == 'Оператива' or b.spec__key  == 'Operational' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
    <br>

    <li class="title-filter" onclick="showFilter('th', 'mimg')">{% trans 'Матеріал корпусу' %}</li>
    <img src="{% static 'product/img/strilka.png' %}" id="mimg" width="25px" style="margin-top: -28px; margin-left: 138px;"></li>
    <div class="filter" id="th">
        {% for b in specifications %}
            {% if b.spec__key  == 'Матеріал корпусу' or b.spec__key  == 'Housing material' %}
                <li class="item-filter">
                    <input type="checkbox" name="specification" value="{{ b.spec__value }}">
                    <span>{{ b.spec__value }}</span>
                </li>
            {% endif %}
        {% endfor %}
    </div>
</ul>